### ISSUE TITLE
Thank you for the great job!!!

### ISSUE THREAD

**Issue by RSanchez996** [ahmetdzdrr/Time-Series-Forecasting-Electricity-Demand#1]
Hi friend, your work looks very good!!! two small doubts: where can I find the dataset? and on the other hand, where is the main script (multi_label_classification.ipynb) you mention?

Thank you very much!!

**Comment by ahmetdzdrr** [comment]
First of all, thank you for kind wishes. I really appreaciate that. 

> First Consider 
- I commited the train and test dataset inside of the electricty_demand folder. 

> Second Consider
- I didn't pay attention when I prepared Usage section. Just a little bit copy & paste issue. So, there isn't multi_label_classification.ipynb file, in fact it's electricty_demand. ipynb file. I'm really sorry about that :)
